homeassistant:
  
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 172.16.0.0/12
    - type: homeassistant

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.207      # Add the IP address of the proxy server
    - 172.16.0.0/12

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.


# Discover some devices automatically
discovery:

#frontend:
frontend: !include themes.yaml 
#template: !include sidebar.yaml

lovelace:
  mode: yaml
  dashboards:
    lovelace-tablet:
      mode: yaml
      title: Tablet
      show_in_sidebar: true
      filename: tablet/lovelace-tablet.yaml
      icon: mdi:tablet
    lovelace-rounded:
      mode: yaml
      title: Rounded
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: rounded/lovelace-rounded.yaml
  resources: 
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /hacsfiles/tabbed-card/tabbed-card.js,                                 type: module },
      { url: /hacsfiles/spotify-card/spotify-card.js,                               type: module },
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,              type: module },
      { url: /hacsfiles/my-cards/my-cards.js,                                       type: module },
      { url: /hacsfiles/upcoming-media-card/upcoming-media-card.js?v=0.4.3,         type: js     },
      { url: '/local/marked.min.js?v=4.2.1',                                        type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.3',                                  type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

# Sensors
sensor: 
  # Weather prediction
  #- platform: yr
  - platform: sonos_upcoming_media
    ip: 192.168.1.215
    max: 2
  - platform: sonarr_upcoming_media
    api_key: f5ec1dd7cb68466d8ffac2b98eb2f432
    host: 192.168.1.207
    port: 8787
    days: 7
    ssl: false
    max: 10
  #Try to get token from 127.0.0.1 on falcon
  - platform: plex_recently_added
    name: plex_recently_added
    token: d1o9w1ZKb2Tip2hPuD8c
    host: 192.168.1.207
    image_resolution: 800
    exclude_keywords:
      - Letterkenny

  - platform: waste_connections
    urlbase: https://api.recollect.net/api/places/E986C39C-C5CD-11EA-8DA2-6CE17286E7FE/services/903/events

  # Minimal configuration of the standard time and date sensor
  - platform: time_date
    display_options:
      - 'date_time_iso'
  # Build on the standard sensor to produce one that can be customized

template:
  - sensor:
      - name: "Date and time"
        state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B %-d, %I:%M %p') }}"
        icon: "mdi:calendar-clock"
      - name: "Date"
        state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B %-d') }}"
        icon: "mdi:calendar-clock"
      - name: "Time"
        state: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M %p') }}"
        icon: "mdi:calendar-clock"
      - name: "PS5"
        icon: "fab:playstation"
        state: >
          {% if is_state('sensor.ps5_sensor', 'ON') %}
            Playing
          {% elif is_state('sensor.ps5_sensor', 'STANDBY') %}
            Standby
          {% else %}
            Off
          {% endif %}
  - sensor:
    - unique_id: sidebar
      state: template
      attributes:
        time: >
          {% set hours = now().strftime('%-I') %}
          {% set minutes = now().strftime('%M') %}
          {% set ampm = now().strftime('%p') %}
          <span class="time">
            {{ hours }}<span class="time-colon">:</span>{{ minutes }}
          </span>
        datum: >
          <span class="date"> 
            {{ states('sensor.date') }}
          </span>
          <hr /> 
        greet: >
          <b>
          {% set time = now().hour %}
          {% if time <= 1 %} Good Night{{'\U0001F611'}}
          {% elif time <= 3 %} Good Night{{'\U0001F62A'}}
          {% elif time <= 5 %} Good Night{{'\U0001F634'}}
          {% elif time <= 7 %} Good Morning {{'\U0001F4A9'}}
          {% elif time <= 9 %} Good Morning {{'\u2615\uFE0F'}}
          {% elif time <= 10 %} Good Morning {{'\U0001F642'}}
          {% elif time <= 13 %} Good Afternoon {{'\U0001F60A'}}
          {% elif time <= 15 %} Good Afternoon {{'\U0001F60E'}}
          {% elif time <= 17 %} Good Afternoon {{'\U0001F44B\U0001F3FB'}}
          {% elif time <= 19 %} Good Evening {{'\U0001F44B\U0001F3FB'}}
          {% elif time <= 22 %} Good Evening {{'\U0001F60C'}}
          {% elif time <= 23 %} Good Evening {{'\U0001F974'}}
          {% else %} Good Evening {{'\U0001F974'}}
          {% endif %}
          </b>
          <hr />
          
# Text to speech 
tts: 
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
lutron_caseta:
  - host: 192.168.1.233
    keyfile: config/lutron_caseta/caseta.key
    certfile: config/lutron_caseta/caseta.crt
    ca_certs: config/lutron_caseta/caseta-bridge.crt

spotcast: 
  sp_dc: !secret spotify_sp_dc
  sp_key: !secret spotify_sp_key

binary_sensor:
  - platform: template
    sensors:
      garage_open:
        value_template: '{{ is_state("cover.garage_door", "open") and state_attr("sun.sun", "elevation") < 4 }}'
        friendly_name: 'Garage is open at night'

monitor_docker:
  - name: Docker
    precision_cpu: 0
    precision_memory_percentage: 0 
    containers:
      - Sonarr
      - zwavejs
      - Unifi
      - Transmission
      - HomeAssistant
    rename: 
      Sonarr: Sonarr
      zwavejs: "Z-Wave JS"
      Unifi-New: "Unifi"
      Transmission: Transmission
      HomeAssistant: "Home Assistant"
    monitored_conditions:
      - version
      - containers_running
      - containers_total
      - state
      - status
      - memory_percentage
      - 1cpu_percentage

# - platform: command_line
#   unique_id: 1644163974631
#   name: ps5_sensor
#   command: 'python ./custom_sensors/ps5.py -q 192.168.1.203'
#   scan_interval: 30

#switch:
#  - platform: command_line
#    switches:
#      playstation:
#        value_template: >
#          {% if value == 'ON' %}
#            Playing
#          {% elif value == 'STANDBY' %}
#            Standby
#          {% else %}
#            Off
#          {% endif %}
#        command_state: 'python ./custom_sensors/ps5.py -q 192.168.1.203'
#        command_on: 'python ./custom_sensors/ps5.py -w -u -1928588545 192.168.1.203'

